version: '3.7'

services:
  postgres-alivelife:
    restart: always
    image: postgres:latest
    volumes:
      - postgres-alivelife-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: loqed-alivelife
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e!
    networks:
      - alivelife-network

  django_gunicorn:
    restart: always
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres-alivelife
    networks:
      - alivelife-network

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django_gunicorn
    volumes:
      - ./app/static:/app/static
      - ./app/media:/app/media
      - /etc/ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - /etc/ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    networks:
      - alivelife-network

volumes: 
  postgres-alivelife-volume:
  static:
  media:

networks:
  alivelife-network:
