name: Deploy para Servidor

on:
  push:
    branches:
      - main  # Ou outra branch de deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout do repositório
    - name: Checkout do Código
      uses: actions/checkout@v3

    # Configuração do SSH
    - name: Configurar SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    # Garantir Diretório no Servidor
    - name: Garantir Diretório no Servidor
      run: |
        ssh -o StrictHostKeyChecking=no root@142.93.72.190 "
        rm -rf /AliveLife &&
        mkdir -p /AliveLife
        "

    # Subir Arquivos para o Servidor
    - name: Subir Arquivos para o Servidor
      run: |
        scp -o StrictHostKeyChecking=no -r ./* root@142.93.72.190:/AliveLife/

    # Construir e Rodar Docker no Servidor
    - name: Construir e Rodar Docker no Servidor
      run: |
        ssh -o StrictHostKeyChecking=no root@142.93.72.190 "
        cd /AliveLife &&
        docker-compose down &&
        docker-compose up -d --build
        "
